### ISSUE TITLE
Doesn't work with rhythmbox 2.97 and Debian wheezy

### ISSUE THREAD

**Issue by Surfoo** [LukeCarrier/rhythmbox-rhythmsub#1]
Hello,

I can't use the plugin with rhythmbox 2.97 and Wheezy... And I don't know python to fix the issue: 

```
Could not find loader 'python3'
```

I changed by _python_ in rhythmsub.plugin, but I have some issues with libraries import

```
Traceback (most recent call last):
  File "/home/user/.local/share/rhythmbox/plugins/rhythmsub/rhythmsub.py", line 17, in <module>
    from subsonic import Server as SubsonicServer
  File "/home/user/.local/share/rhythmbox/plugins/rhythmsub/subsonic.py", line 13, in <module>
    import urllib.parse
ImportError: No module named parse

(rhythmbox:9538): libpeas-WARNING **: Error loading plugin 'rhythmsub'
```

**Comment by LukeCarrier** [comment]
The root cause of this issue is that the plugin was authored to target Rhythmbox 3, which uses Python 3 for its plugin system. Previous versions used Python 2, which is why changing the loader entry allows the plugin to be registered.

I'm afraid though this plugin isn't likely to be maintained for a while, as there are bugs in libraries used by the Rhythmbox loader which render it unsuitable for the library system in Subsonic. It's impossible to import larger libraries because the underlying code (gvfs-http, which is part of GNOME) is unstable. Sorry :unamused:
